language: generic
sudo: required

services:
  - docker

addons:
  sonarcloud:
    organization: "twasi"

jobs:
  include:
    - stage: docker
      script:
        - 'docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"'
        - "docker build ."
        - "docker push twasi/twasi-panel"

stages:
  - docker
